update creature_template set name = 'Senhor da Heranca' where entry=90000;

update item_template set name='Dever Sagrado de DalTornar Venerável' where entry=942945;
update item_template set name='Dever do capitão da dignidade' where entry=942947;
update item_template set name='Ombro do campeão Herodes' where entry=942950;
update item_template set name='Brafoneiras dos Elementos Místicos' where entry=942951;
update item_template set name='Mão de justiça rápida' where entry=942991;
update item_template set name='Campeão do dinheiro real reforÃ§ado' where entry=944092;
update item_template set name='Canhão manual anão aprimorado' where entry=944093;
update item_template set name='Big stick da Jordãnia' where entry=944095;
update item_template set name='Brafoneiras da prisão fortificada' where entry=944099;
update item_template set name='Espaldares Sancteforge em perfeitas condições' where entry=944100;
update item_template set name='Brafoneiras Velhas dos Cinco Trovões' where entry=944102;
update item_template set name='Espaldares Coração-Ferozes Duráveis' where entry=944105;
update item_template set name='Peitoral do Campeão Reparador da Morte' where entry=948677;
update item_template set name='Colete de Elementos Místicos' where entry=948683;
update item_template set name='Venerável McGowan Mace' where entry=948716;
update item_template set name='Correio Elementar Místico' where entry=961936;
update item_template set name='Chapéu Manchado de Shadowcraft' where entry=961937;
update item_template set name='Perneiras de destruição manchadas' where entry=962024;
update item_template set name='Calças escuras' where entry=962026;
update item_template set name='Perneiras da Névoa Mortal Remendadas' where entry=962029;
update item_template set name='Manto de Gárgula de Pele de Pedra Usada' where entry=962038;
update item_template set name='Cabo herdado do barão preto' where entry=962039;
update item_template set name='Rasgo sangueneo de Stratholme' where entry=969893;
update item_template set name='Campeão do dinheiro real reforçado' where entry=944092;
update item_template set name='O Abençoado Martelo da Graça' where entry=944094;
update item_template set name='Perneiras de destruição manchadas' where entry=962024;
